# Generated by Django 5.2.1 on 2025-10-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='상품 이미지')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='상품 코드')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='재고')),
                ('description', models.TextField(blank=True, verbose_name='상품 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['-created_at'],
            },
        ),
    ]
